@startuml
starter -> AppRegLauncher:init
AppRegLauncher -> AlmComponentInit:init
AlmComponentInit -> AlmComponentInit:initAgentAlm
AlmComponentInit -> AlmComponentInit:initLocalAlm
AlmComponentInit -> AlmCallbackProxyImpl


@enduml