---
svc-gov-sdk:
  alm:
    enabled: false
  appKey: pg-app-demo2
  unionGatewayUrl: http://gxfw-yh02-dev.yh-union-gateway.devgw.yonghui.cn/api
#  retry:
#    enabled: false
#    shardingEnabled: false
#    shardingColumn: db_tag
  secret: 12345678
yh:
  metrics:
    meters:
      test-counter1:
        key: yh_infra_demosb1_counter_test1_dev
        type: counter
      test-gauge1:
        key: yh_infra_demosb1_gauge_test1_dev
        type: gauge
      test-gauge3:
        key: yh_infra_demosb1_gauge_test3_dev
        type: gauge
        dimensions:
        - "shop=adidas"
        - "shop=nike"
      test-timer1:
        key: yh_infra_demosb1_timer_test1_dev
        type: timer
        dimensions:
        - "function=" 
      test-summary1:
        key: yh_infra_demosb1_summary_test1_dev
        type: summary
          
management:
  metrics:
    binders:
      jvm:
        enabled: false          
      log4j2:
        enabled: false
      uptime:
        enabled: false
      processor:
        enabled: false
    kafka:
      consumer:
        enabled: false
sdk-demo:
  sdk-enabled: true
  app-id: pg-app-demo1
  app-secret: 12345678
  server:
    host: localhost-1
    ip: 10.0.0.1
  chain:
    mq:
      topic:
        receive: MQ_GSDK_DEMO_${sdk-demo.app-id}
        forward: MQ_GSDK_DEMO_${sdk-demo.chain.next.app-id}
    next:
      app-id: pg-app-demo2
      msg-type: 
      service: 
        id: app-demo-spring-boot1-${spring.profiles.active}-${sdk-demo.chain.next.app-id}
        url:   
    node:
      name: ${sdk-demo.app-id}-node1
server:
  port: 9001

spring: 
  datasource:
    dbcp2:
      connection-properties: characterEncoding=utf8
      initial-size: 5
      max-total: 50
      max-wait-millis: 10000
      validation-query: "SELECT 1"
    type: org.apache.commons.dbcp2.BasicDataSource
    url: "jdbc:mysql://localhost:3306/db_retry_service_dev?useUnicode=true&characterEncoding=utf-8&useSSL=false&autoReconnect=true"
    username: root
    password: 602231903
  cloud:
    consul:
      discovery:
        catalog-services-watch:
          enabled: false
        catalogServicesWatchDelay: 30000
        deregister: true
        enabled: true
        health-check-critical-timeout: 30m
        health-check-interval: 15s
        instance-id: "m-${spring.cloud.client.hostname}-${spring.application.name}-${spring.cloud.consul.host}-${spring.cloud.consul.port}"
        prefer-ip-address: true
        register: false
        service-name: "test-app-${spring.application.name}-${spring.profiles.active}"
      #        tags: app=${spring.application.name},env=${spring.profiles.active},project=YhInfra,product=YhInfra
      enabled: true
      host: 10.251.77.93
      port: 8500
      retry:
        retryInterval: 6000
        enable: true
    discovery:
      client:
        composite-indicator:
          enabled: false
    
    